version: '2.4'

services:
  collector:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - collector-db:/app/collected_data
    environment:
      - TELEGRAM_BOT_TOKEN=YOUR_BOT_TOKEN
      - TELEGRAM_CHAT_ID=YOUR_CHAT_ID

volumes:
  collector-db: